import "@fontsource/jetbrains-mono"
import "@fontsource/jetbrains-mono/300.css"
import "@fontsource/jetbrains-mono/200.css"
import "@fontsource/jetbrains-mono/800.css"
import "@fontsource/fira-code"
import "@fontsource/fira-code/300.css"
