FROM node:18-alpine3.16
WORKDIR /app
COPY ["package.json", "package-lock.json*", "./"]
RUN  npm install --registry http://registry.npmmirror.com  --force
COPY . .
EXPOSE 12833
CMD ["npm", "run", "start"]
